"""empty message

Revision ID: 47de774ebfa0
Revises: 
Create Date: 2025-03-21 00:11:58.578835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47de774ebfa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
