"""empty message

Revision ID: c8b82f43e72b
Revises: ea523590e992
Create Date: 2025-03-24 23:26:15.584970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c8b82f43e72b'
down_revision = 'ea523590e992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_certificate')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('original_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('data')
        batch_op.drop_column('content_type')

    op.create_table('_alembic_tmp_certificate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('extracted_text', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
