"""Initial tables

Revision ID: ea523590e992
Revises: 47de774ebfa0
Create Date: 2025-03-24 23:24:02.291666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ea523590e992'
down_revision = '47de774ebfa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    op.drop_table('certificates')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('original_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('data')
        batch_op.drop_column('content_type')

    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=1)

    # ### end Alembic commands ###
